### PR TITLE
Use example rows from multiple example tables

### PR DESCRIPTION
**Pull request by jonfinerty**
Fixes a crash with having multiple example tables where it would only process the first example table

### CODE REVIEW

**Comment by kevinrood** [comment]
Fixes #7

**Comment by jonfinerty** [comment]
Sorry to nag, but any progress on merging this?

**Comment by dsvishchov** [comment]
Just made the same fix, and wanted to raise the same pull request :) @kevinrood could you pls merge this simple fix into master?

**Comment by kevinrood** [comment]
@jonfinerty @dsvishchov thank you both. I apologize for the delay.

**Comment by dsvishchov** [comment]
Awesome. Could you also push an updated gem version?

**Comment by kevinrood** [comment]
Just pushed `0.8.3` :smile:

**Pull request merged**
