### PR TITLE
include PID-based flowId to play nice with parallel_cucumber

### PR DESCRIPTION
**Pull request by aklossrbh**
Things get pretty messed up when running parallel cucumber; scenarios move around between suites randomly.

### CODE REVIEW

**Comment by kevinrood** [comment]
@aklossrbh first of all, thank you for your contribution!

It would likely be more in line with the existing style to use something like this:

``` ruby
def test_suite_started(test_suite_name)
  render_output("##teamcity[testSuiteStarted flowId='#{flow_id}' name='#{teamcity_escape(test_suite_name)}' timestamp='#{timestamp}']")
end

# ...

private

def flow_id
  Process.pid
end
```

What would you think about that?

**Comment by aklossrbh** [comment]
I'm good with it; I've pushed an updated change which has passed in our CI.

**Comment by kevinrood** [comment]
@aklossrbh very sorry this took so long to merge. Would you be in a position to run the version in master with your test suite and let me know if everything is working for you as expected? Your pull request landed in `master` along with one more.

**Comment by aklossrbh** [comment]
No worries.  I ran this through our CI server and it reported the same number of tests, etc.  When do you think you'll publish an updated gem so we can drop our inlined fork entirely?

**Comment by kevinrood** [comment]
@aklossrbh this pull request is now available in version 0.8.2 of the gem, which was just published :smile:

**Pull request merged**
